version: '3.8'

services:
  myapp-postgres-master:
    image: bitnami/postgresql-repmgr:17.2.0
    container_name: master-1
    volumes:
      - /data/postgresql_master:/bitnami/postgresql
      - /data/repmgr_master:/opt/bitnami/repmgr/conf
    env_file: 
      - path: ./postgres-master/my_env.env
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      myapp-network:
        #ipv4_address: 172.20.0.21


  myapp-postgres-slave:
    image: bitnami/postgresql-repmgr:17.2.0
    container_name: slave-1
    volumes:
      - /data/postgresql_slave:/bitnami/postgresql
      - /data/repmgr_slave:/opt/bitnami/repmgr/conf
    env_file: 
      - path: ./postgres-slave/my_env.env
    depends_on:
      - myapp-postgres-master
    restart: always
    ports:
      - "5433:5432"
    networks:
      myapp-network:
        #ipv4_address: 172.20.0.22


  myapp-frontend:
    build:
      context: ./frontend/Finance_frontend/
    ports:
      - "3000:3000"
    depends_on:
      - myapp-postgres-master
      - myapp-backend
    networks:
      myapp-network:
        #ipv4_address: 172.20.0.32

  nginx:
    build:
      context: ./frontend/Finance_frontend/nginx
    ports:
      - "80:80"
    depends_on:
      - myapp-frontend
    networks:
      myapp-network:


  # postgres-exporter-master:
  #   image: prometheuscommunity/postgres-exporter:latest
  #   container_name: exporter-master-1
  #   ports:
  #     - 9187:9187
  #       # volumes:
  #     #- ./custom_queries.yml:/etc/postgres_exporter/queries.yaml
  #   environment:
  #     DATA_SOURCE_URI: "master-1:5432/feenance?sslmode=disable"
  #     DATA_SOURCE_USER: repmgr 
  #     DATA_SOURCE_PASS: 123456
  #   networks:
  #     myapp-network:
  #   depends_on:
  #     - myapp-postgres-master


  # postgres-exporter-slave:
  #   image: prometheuscommunity/postgres-exporter:latest
  #   container_name: exporter-slave-1
  #   ports:
  #     - 9188:9187
  #       # volumes:
  #     #- ./custom_queries.yml:/etc/postgres_exporter/queries.yaml
  #   environment:
  #     DATA_SOURCE_URI: "slave-1:5433/feenance?sslmode=disable"
  #     DATA_SOURCE_USER: repmgr
  #     DATA_SOURCE_PASS: 123456
  #   networks:
  #     myapp-network:
  #   depends_on:
  #     - myapp-postgres-slave
  myapp-backend:
    build:
      context: ./backend/FinanceApp/
    env_file:
      - ./backend/FinanceApp/my_env.env
    ports:
      - "8000:8000"
    networks:
      myapp-network:
        # ipv4_address: 172.20.0.31
    depends_on:
      - myapp-postgres-master
      - myapp-postgres-slave

networks:
  myapp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
