version: '3.8'

services:
  myapp-postgres-master:
    #image: postgres:16
    build: ./postgres-master/
    container_name: master-1
      #volumes:
      #- /data/postgresql_master:/bitnami/postgresql
      #- /data/repmgr_master:/opt/bitnami/repmgr/conf
    env_file: 
      - path: ./postgres-master/my_env.env
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      myapp-network:


  myapp-postgres-slave:
    #image: postgres:16
    build: ./postgres-slave/
    container_name: slave-1
      #volumes:
      #- /data/postgresql_slave:/bitnami/postgresql
      #- /data/repmgr_slave:/opt/bitnami/repmgr/conf
    env_file: 
      - path: ./postgres-slave/my_env.env
    depends_on:
      - myapp-postgres-master
    restart: always
    ports:
      - "5433:5432"
    networks:
      myapp-network:


  myapp-frontend:
    build:
      context: ./frontend/Finance_frontend/finance-app
    container_name: fronted
    ports:
      - "3000:3000"
      - "80:80"
    depends_on:
      - myapp-postgres-master
      - myapp-backend
    networks:
      myapp-network:

  postgres-exporter-master:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: exporter-master-1
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_URI: "master-1:5432/feenance?sslmode=disable"
      DATA_SOURCE_USER: feenance
      DATA_SOURCE_PASS: 123456
    networks:
      myapp-network:
    depends_on:
      - myapp-postgres-master

  postgres-exporter-slave:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: exporter-slave-1
    ports:
      - 9188:9187
    environment:
      DATA_SOURCE_URI: "slave-1:5433/feenance?sslmode=disable"
      DATA_SOURCE_USER: feenance
      DATA_SOURCE_PASS: 123456
    networks:
      myapp-network:
    depends_on:
      - myapp-postgres-slave

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'


  myapp-backend:
    build:
      context: ./backend/FinanceApp/
    container_name: backend
    env_file:
      - ./backend/FinanceApp/my_env.env
    ports:
      - "8000:8000"
    command: >
       sh -c 'python3 ./manage.py migrate &&
       python3 ./manage.py runserver 0.0.0.0:8000'
    networks:
      myapp-network:
        # ipv4_address: 172.20.0.31
    depends_on:
      - myapp-postgres-master
      - myapp-postgres-slave
  
  prometheus-server:
    build: ./prometheus-server/
    container_name: prometheus-server
    volumes:
      - /prometheus-data/:/prometheus/
    ports:
      - "9090:9090"
    networks:
      myapp-network:
    depends_on:
      - myapp-backend

  grafana-server:
    build: ./grafana-server/
    container_name: grafana-server
    volumes:
      - /grafana-data/:/var/lib/grafana/
      - ./grafana-server/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456
    ports:
      - "3001:3000"
    networks:
      myapp-network:
    depends_on:
      - prometheus-server

networks:
  myapp-network:
    driver: bridge
