FROM postgres:16
COPY ./postgresSlave.sh /docker-entrypoint-initdb.d/postgresSlave.sh
RUN mkdir /backups
RUN mkdir /scripts
COPY ./backup.sh /scripts/backup.sh
RUN chmod 0777 /docker-entrypoint-initdb.d/postgresSlave.sh
RUN chmod 0777 /scripts/backup.sh
