FROM postgres:16
COPY ./postgresMaster.sh /docker-entrypoint-initdb.d/postgresMaster.sh
RUN chmod 0666 /docker-entrypoint-initdb.d/postgresMaster.sh
#COPY --chown=postgres:postgres PostgresqlDict/* /usr/share/postgresql/16/tsearch_data/
